### ISSUE TITLE
Cross compiling alternative

### ISSUE THREAD

**Issue by KevinCain** [NSchertler/OnlineSurfaceReconstruction#6]
I note your three deployment branches, but personally I'm a fan of cross-compiling and wanted to see if any steps along that path were of interest.

Mostly I have compiled for Windows x64 targets from Linux, but in the case of OSR, I can imagine people wanting to target RPi, et cetera.

I'm happy to try this on my own but wanted to see how this may fit or conflict with the OSR roadmap, or if there are any advice (or roadblocks!) I should keep in mind as I start -- e.g., the need to transition Zenity browser support in Linux to a canonical NanoGUI file dialog for Windows.

**Comment by NSchertler** [comment]
The deployment branches are populated from the continuous integration providers.

From the OSR end, compilation for other platforms should not be a big problem. The only requirement is that you need an OpenGL 3.3-capable graphics card for interactive mode and preferably an OpenMP-capable compiler. However, performance on small computers like RPi might be too low to allow real interactivity (especially since we rely on a huge amount of parallelization for the computationally heavy parts). We haven't planned to explore this direction, but you are welcome to try.

For the NanoGUI part, I am not very sure. You already noticed that some parts of NanoGUI choose an implementation based on the platform. @wjakob is the better person to ask those questions.
